spring:
  datasource:   #配置数据库连接的四个信息，这里使用的是SpringBoot内置的数据库连接池Hikari
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myshop
    username: root
    password: admin
  jpa:
    database: mysql         #指定数据库
    show-sql: true          #是否显示SQL语句
    generate-ddl: false     #是否在启动时初始化schema，默认为false
    open-in-view: false     #是否注册OpenEntityManagerInViewInterceptor，绑定JPA EntityManager到请求线程中，默认为: true
    hibernate:
      ddl-auto: update      #用于指定数据库表生成策略
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  redis:
    host: 127.0.0.1
    port: 6379