server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myshop?useSSL=false&characterEncoding=UTF-8
    username: root
    password: admin
  redis:
    host: 127.0.0.1
    port: 6379
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main #重启目录
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  resources:
    static-locations:
      - file:G:\temp\images   #访问系统外部资源，将该目录下的文件映射到系统下
      - classpath:/static/
mybatis-plus:
  type-aliases-package: com.hrp.domain
file:
  upload:
    path: G:\temp\images\   #文件上传目标路径
    allowTypes:             #文件上传允许的类型
      - image/jpeg
      - image/png
      - image/jpg
      - image/bmp